project:
  type: website
  output-dir: docs

jupyter:
  kernel: ml-env

website:
  navbar:
    title: "EDS 232"
    right:
      - href: index.qmd
        text: Home
      - text: Discussion
        menu:
          - text: week 0
            href: discussion/week0.qmd
          - text: week 1
            href: discussion/week1.qmd
      - text: Weekly Labs
        menu:
          - text: Lab Rubric
            href: www/lab_rubric.pdf
          - text: Weekly Labs
            href: labs/lab_instructions.qmd     
     
      - icon: github
        href: https://github.com/MaRo406/eds-232-machine-learning
        target: _blank

  page-footer:
    background: dark

format:
  html:
    theme: meds-website-styles.css
    toc: true
    toc-location: left
    title-block-banner: true
    page-layout: full

editor: source
