---
title: "Assignments"
---

<p style="color: #ba5e00">

Assigned readings and labs will be posted to this page on a weekly basis.

</p>

## Week 1

### Slides:

-   Lecture 1: [Course Welcome and Intro](https://ucsb.app.box.com/file/1409385618047)
-   Lecture 2: [Linear Regression I](https://ucsb.box.com/s/vdazgd97wgadhmd8wouwb4ktborcced3)

### Assigned Reading:

-   [HOML Ch. 1 (1.1 - 1.4)](https://bradleyboehmke.github.io/HOML/intro.html)

*Supplementary Reading*

-   [*Get Started with TidyModels - Section 2.*](https://www.tidymodels.org/start/recipes/)

### Lab:

-   [Link to .Rmd](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab1.Rmd)

## Week 2

### Slides:

Lecture 1: [Model Process and Ridge Regression](https://ucsb.box.com/s/ec2qc93xmctyqqp3g1p7kokcieqobguj)

Lecture 2: [Lab 2 - Linear Regression II](https://ucsb.box.com/s/us6c7w0ad4wllmk0jnz9wow1x18x5anc)

### Assigned Reading:

-   [HOML Ch. 2](https://bradleyboehmke.github.io/HOML/process.html#resampling)
-   [HOML Ch. 4 (4.2-4.5)](https://bradleyboehmke.github.io/HOML/linear-regression.html#simple-linear-regression)
    -   Review of basic regression. Feel free to skim this a bit if you feel good about your understanding of linear regression.

*Supplementary Reading*

-   [Tidy Models in R Ch. 3 (3.3-3.5)](https://www.tmwr.org/base-r.html#tidiness-modeling)
    -   Intro to Tidy Modeling. Provides some context for Lab 1 and beyond.

### Lab:

-   [Link to .Rmd](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab2.Rmd)

### Discussion:

-   Download discussion template [here](discussion/week2_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/file/d/1ZqxTMwyDz910ryBY4OwrLmUy7Cgtljm5/view?usp=drive_link)
-   Download completed discussion [here](discussion/week2.Rmd)

## Week 3

### Slides:

-   Lecture: [Classification and Logistic Regression](https://ucsb.box.com/s/9hpdbhrwu8wxvhg1uf9r9qwdmhtzkztr)

### Assigned Reading:

-   [HOML Ch. 5](https://bradleyboehmke.github.io/HOML/logistic-regression.html), [HOML Ch. 6](https://bradleyboehmke.github.io/HOML/regularized-regression.html)

### Lab:

-   [Demo](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab3_Demo.Rmd)

    -   [Demo key](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab3_Demo.Rmd)

-   [Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab3.Rmd)

### Discussion:

-   Download completed discussion [here](discussion/week3.Rmd)

## Week 4

### Slides:

-   Lecture: [KNN and Decision Trees](https://ucsb.box.com/s/426snv5kax3npymzafbib3cjug4sdnky)

### Assigned Reading:

-   [HOML Ch. 8](https://bradleyboehmke.github.io/HOML/knn.html), [HOML Ch. 9](https://bradleyboehmke.github.io/HOML/DT.html)

### Lab:

-   [Link to .Rmd](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab4.Rmd)

### Discussion:

-   Download discussion template [here](discussion/week4_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/drive/folders/1lkfNW4SpQXsGJI_U1WzocCVkibwFpbGd?usp=drive_link)
-   Download completed discussion [here](discussion/week4.Rmd)

## Week 5

### Slides:

-   Lecture: [Guest Lecture](https://ucsb.box.com/s/spuc0fxqjauu0aqre1h1q7u7lrlp9g0j)

### Assigned Reading:

-   [HOML Ch. 8](https://bradleyboehmke.github.io/HOML/knn.html), [HOML Ch. 9](https://bradleyboehmke.github.io/HOML/DT.html) (*continued from last week*)

### Lab:

-   [Demo key](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab5_Demo.Rmd)

-   [Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab5.Rmd)

### Discussion:

-   Download discussion template [here](discussion/week5_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/drive/folders/15A89wGnu8l_hjR_DQLCwaNXjddOnRfn8?usp=drive_link)
-   Download completed discussion [here](discussion/week5.Rmd)

## Week 6

### Slides:

-   Lecture: [Bagging and Random Forests](https://ucsb.box.com/s/8btqbb9k518w1wp8k5iw39fi4sq2dzw6)

### Assigned Reading:

-   [HOML Ch.10](https://bradleyboehmke.github.io/HOML/bagging.html), [HOML Ch.11](https://bradleyboehmke.github.io/HOML/random-forest.html)

### Lab:

-   [Demo](labs/Lab5_Demo2.Rmd)
-   [Demo Data](https://drive.google.com/drive/folders/1T51L6kBQnYXaqSRGAzTJtEWh7dw9zAiz?usp=sharing)
-   [Demo Key](labs/Lab5_Demo2_key.Rmd)

### Discussion:

-   Download discussion template [here](discussion/week6_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/drive/folders/1zaSFHu2JCTK4dFtKJoSZ5d55SbHmMgc1?usp=sharing)
-   Download completed discussion [here](discussion/week6.Rmd)

## Week 7

### Slides:

-   Lecture: [Boosted Trees](https://ucsb.box.com/s/roha0hdtyc7548qkttvfidjj4o26s5n9)
-   Lab: [Variables and Hyperparameters](https://ucsb.box.com/s/vekfqcoxebxwvri9ru1a9ovumxa3rnry)

### Assigned Reading:

-   [HOML Ch. 12](https://bradleyboehmke.github.io/HOML/gbm.html#a-sequential-ensemble-approach)

### Lab:

-   [Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab6.Rmd)

<!-- -->

-   [Elith et al. 2008](https://ucsb.box.com/s/05wbobx731r6tq0yvsqbtd6l3769sdvr)

### Discussion:

-   Download discussion template [here](discussion/week7_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/drive/folders/1mOrwJmefHKRtTVJsSEgzQiENO4h_RLmd?usp=sharing)
-   Download completed discussion [here](discussion/week7.Rmd)

## Week 8

### Slides:

-   Lecture: [Clustering](https://ucsb.box.com/s/97f5w8opuzyxc064htu1gcjqiym9ssrb)

### Assigned Reading:

-   [HOML Ch. 20](https://bradleyboehmke.github.io/HOML/kmeans.html), [HOML Ch. 21](https://bradleyboehmke.github.io/HOML/hierarchical.html)

### Lab:

-   [Demo/Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab7_Demo_InClass.Rmd)
    -   [Completed demo](https://github.com/MaRo406/eds-232-machine-learning/blob/main/labs/Lab7_Demo_InClass_complete.Rmd)

### Discussion:

-   Download discussion template [here](discussion/week8_skeleton.Rmd)
-   Download discussion data [here](https://drive.google.com/drive/folders/1kBySK4clcG5RvzmKpxzvPp_nW0Rqq-W6?usp=sharing)

## Week 9

### Slides:

-   Lecture: [Support Vector Machines](https://ucsb.box.com/s/ogq5ubj3umkx5igb8ph3xnma4q0lrhim)

### Assigned Reading:

-   [HOML Ch. 14](https://bradleyboehmke.github.io/HOML/svm.html#feature-interpretation-2)

### Lab:

-   [Demo](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab8_Demo.Rmd)

    -   [Key](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab8_Demo_key.Rmd)

-   [Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab8.Rmd)

    -   [Metadata](https://github.com/MaRo406/eds-232-machine-learning/blob/main/data/covtype_metadata.info)

### Discussion:

-   No discussion this week

## Week 10

### Slides:

-   Lecture: Guest Lecture
-   Lecture:

### Assigned Reading: 

-   [HOML Ch. 13](https://bradleyboehmke.github.io/HOML/deep-learning.html)
